ListenAddr = ":8080"
DockerURL = "tcp://127.0.0.1:3375"

[[Extensions]]
Name = "nginx"
ConfigPath = "/etc/nginx/nginx.conf"
PidPath = "/var/run/nginx.pid"
BackendOverrideAddress = "172.17.0.1"
MaxConn = 1024
Port = 80
NginxPlusEnabled = false
