interlock:
    image: ehazlett/interlock:1.1.0
    command: run -c /bin/config.toml
    ports:
        - 8080
    volumes:
        - ./config.toml:/etc/interlock/config.toml
        - nginx:/etc/nginx

nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
        - 80:80
    labels:
        - "interlock.ext.name=nginx"
    links:
        - interlock:interlock
    volumes:
        - nginx:/etc/nginx

app:
    image: ehazlett/docker-demo:latest
    ports:
        - 8080
    labels:
        - "interlock.hostname=test"
        - "interlock.domain=local"
