ListenAddr = ":8080"
DockerURL = "unix:///var/run/docker.sock"

[[Extensions]]
Name = "haproxy"
ConfigPath = "/usr/local/etc/haproxy/haproxy.cfg"
PidPath = "/var/run/haproxy.pid"
TemplatePath = "/etc/interlock/haproxy.cfg.template"
BackendOverrideAddress = "172.17.0.1"
MaxConn = 1024
Port = 80
AdminUser = "admin"
AdminPass = "interlock"
